# Generated by Django 4.2.1 on 2023-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('genre', models.CharField(choices=[('M', 'Monsieur'), ('F', 'Madame')], default='aucun', max_length=2)),
                ('promotion', models.CharField(choices=[('L1-I', 'Licence 1 Info'), ('L1-F', 'Licence 1 Fisc'), ('L2-C', 'Licence 2 Conception'), ('L2-R', 'Licence 1 Reseau')], default='L1-I', max_length=12)),
                ('status', models.CharField(default='encours', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
