# Generated by Django 4.2.1 on 2023-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='genre',
            field=models.CharField(choices=[('M', 'Monsieur'), ('F', 'Madame')], default='aucun', max_length=1),
        ),
        migrations.AlterField(
            model_name='students',
            name='promotion',
            field=models.CharField(choices=[('L1-I', 'Licence 1 Info'), ('L1-F', 'Licence 1 Fisc'), ('L2-C', 'Licence 2 Conception'), ('L2-R', 'Licence 1 Reseau')], default='L1-I', max_length=7),
        ),
    ]
