# Generated by Django 4.2.1 on 2023-05-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0002_alter_students_genre_alter_students_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.IntegerField(choices=[(1, 'Encours'), (2, 'En attente'), (3, 'Terminer')], default=1),
        ),
    ]
